local evolved = require("evolved")
local fragments = require("fragments")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("enemy")
	:set(fragments.transform)
	:set(fragments.collectionfactory_url, "/entities#player")
	:set(fragments.game_objects_scheme, { ["/fill"] = true, ["/root"] = true })
	:set(fragments.color, { ["/fill#fill"] = color.get_color("#EE6F6F"), ["/root#sprite"] = color.get_color("#612C2C") })
	:set(fragments.physics)
	:set(fragments.velocity)
	:set(fragments.health, 50)
	:set(fragments.health_max, 50)
	:set(fragments.remove_on_death)
	:set(fragments.collision)
	:set(fragments.enemy_visual)
	:set(fragments.panthera_file, require("entity.enemy.enemy_panthera"))
	:spawn()
