local evolved = require("evolved")
local components = require("components")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("bullet")
	:set(components.transform)
	:set(components.collectionfactory_url, "/entities#bullet")
	:set(components.color, color.get_color("#EE6F6F"))
	:set(components.physics)
	:set(components.velocity)
	:set(components.lifetime, 1)
	:spawn()
