local evolved = require("evolved")
local components = require("components")
local color = require("druid.color")

local explosion = require("entities.explosion.explosion")

return evolved.builder()
	:prefab()
	:name("bullet")
	:set(components.transform)
	:set(components.collectionfactory_url, "/entities#bullet")
	:set(components.color, { ["/root#sprite"] = color.get_color("#EE6F6F") })
	:set(components.physics)
	:set(components.velocity)
	:set(components.spawn_on_destroy, explosion)
	:set(components.lifetime, 1)
	:set(components.collision)
	:set(components.on_collision_damage, 1)
	:set(components.on_collision_remove)
	:spawn()
