local evolved = require("evolved")
local components = require("components")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("enemy")
	:set(components.transform)
	:set(components.collectionfactory_url, "/entities#player")
	:set(components.color, color.get_color("#FEAF6F"))
	:set(components.physics)
	:set(components.velocity)
	:set(components.health, 50)
	:set(components.health_max, 50)
	:set(components.collision)
	:set(components.remove_on_death)
	:spawn()
