local evolved = require("evolved")
local components = require("components")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("enemy")
	:set(components.transform)
	:set(components.collectionfactory_url, "/entities#player")
	:set(components.game_objects_scheme, { ["/fill"] = true, ["/root"] = true })
	:set(components.color, { ["/fill#fill"] = color.get_color("#EE6F6F"), ["/root#sprite"] = color.get_color("#612C2C") })
	:set(components.physics)
	:set(components.velocity)
	:set(components.health, 50)
	:set(components.health_max, 50)
	:set(components.collision)
	:set(components.remove_on_death)
	:set(components.panthera_file, require("entities.enemy.enemy_panthera"))
	:set(components.enemy_visual)
	:spawn()
