local evolved = require("evolved")
local components = require("components")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("player")
	:set(components.transform)
	:set(components.collectionfactory_url, "/entities#player")
	:set(components.game_objects_scheme, { ["/root"] = true })
	:set(components.color, { ["/root#sprite"] = color.get_color("#EE6F6F") })
	:set(components.physics)
	:set(components.velocity)
	:set(components.physics_movement_controller)
	:set(components.shooter_controller)
	:spawn()
