local evolved = require("evolved")
local fragments = require("fragments")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("player")
	:set(fragments.transform)
	:set(fragments.collectionfactory_url, "/entities#player")
	:set(fragments.game_objects_scheme, { ["/root"] = true })
	:set(fragments.color, { ["/root#sprite"] = color.get_color("#EE6F6F") })
	:set(fragments.physics)
	:set(fragments.velocity)
	:set(fragments.physics_movement_controller)
	:set(fragments.shooter_controller, { prefab = require("entities.bullet.bullet"), cooldown = 0 })
	:spawn()
