return {
    format = "json",
    data = {
        animations = {
            {
                duration = 1,
                animation_id = "default",
                animation_keys = {
                },
            },
            {
                duration = 50,
                animation_id = "idle",
                animation_keys = {
                    {
                        key_type = "tween",
                        node_id = "enemy21/root",
                        end_value = -450,
                        duration = 1.64,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy21/root",
                        end_value = 475,
                        duration = 1.64,
                        property_id = "position_y",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy1/root",
                        end_value = -435,
                        duration = 4.99,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy1/root",
                        end_value = 170,
                        duration = 4.99,
                        property_id = "position_y",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy2/root",
                        end_value = -135,
                        duration = 6.15,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy3/root",
                        end_value = -135,
                        duration = 6.15,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy4/root",
                        end_value = -135,
                        duration = 6.15,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        node_id = "enemy5/root",
                        end_value = -135,
                        duration = 6.15,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        start_time = 1.64,
                        node_id = "enemy21/root",
                        property_id = "position_y",
                        end_value = 275,
                        duration = 3.33,
                        easing = "outsine",
                        start_value = 475,
                    },
                    {
                        key_type = "tween",
                        start_time = 1.64,
                        node_id = "enemy21/root",
                        property_id = "position_x",
                        end_value = -460,
                        duration = 9.47,
                        easing = "outsine",
                        start_value = -450,
                    },
                    {
                        key_type = "tween",
                        start_time = 4.97,
                        node_id = "enemy21/root",
                        property_id = "position_y",
                        end_value = -480,
                        duration = 6.14,
                        easing = "outsine",
                        start_value = 275,
                    },
                    {
                        key_type = "tween",
                        start_time = 4.99,
                        node_id = "enemy1/root",
                        property_id = "position_x",
                        end_value = -135,
                        duration = 1.16,
                        easing = "outsine",
                        start_value = -135,
                    },
                    {
                        key_type = "tween",
                        start_time = 6.15,
                        node_id = "enemy1/root",
                        property_id = "position_x",
                        end_value = 70,
                        duration = 15.88,
                        easing = "outsine",
                        start_value = -135,
                    },
                    {
                        key_type = "tween",
                        start_time = 6.15,
                        node_id = "enemy2/root",
                        property_id = "position_x",
                        end_value = 70,
                        duration = 15.88,
                        easing = "outsine",
                        start_value = -135,
                    },
                    {
                        key_type = "tween",
                        start_time = 6.15,
                        node_id = "enemy3/root",
                        property_id = "position_x",
                        end_value = 70,
                        duration = 15.88,
                        easing = "outsine",
                        start_value = -135,
                    },
                    {
                        key_type = "tween",
                        start_time = 6.15,
                        node_id = "enemy4/root",
                        property_id = "position_x",
                        end_value = 70,
                        duration = 15.88,
                        easing = "outsine",
                        start_value = -135,
                    },
                    {
                        key_type = "tween",
                        start_time = 6.15,
                        node_id = "enemy5/root",
                        property_id = "position_x",
                        end_value = 70,
                        duration = 15.88,
                        easing = "outsine",
                        start_value = -135,
                    },
                    {
                        key_type = "tween",
                        start_time = 11.11,
                        node_id = "enemy21/root",
                        property_id = "position_y",
                        end_value = -465,
                        duration = 5.19,
                        easing = "outsine",
                        start_value = -480,
                    },
                    {
                        key_type = "tween",
                        start_time = 11.11,
                        node_id = "enemy21/root",
                        property_id = "position_x",
                        end_value = 455,
                        duration = 5.19,
                        easing = "outsine",
                        start_value = -460,
                    },
                    {
                        key_type = "tween",
                        start_time = 16.3,
                        node_id = "enemy21/root",
                        property_id = "position_y",
                        end_value = 105,
                        duration = 4.21,
                        easing = "outsine",
                        start_value = -465,
                    },
                    {
                        key_type = "tween",
                        start_time = 16.3,
                        node_id = "enemy21/root",
                        property_id = "position_x",
                        end_value = 460,
                        duration = 10.15,
                        easing = "outsine",
                        start_value = 455,
                    },
                    {
                        key_type = "tween",
                        start_time = 20.51,
                        node_id = "enemy21/root",
                        property_id = "position_y",
                        end_value = 460,
                        duration = 5.94,
                        easing = "outsine",
                        start_value = 105,
                    },
                    {
                        key_type = "tween",
                        start_time = 22.03,
                        node_id = "enemy1/root",
                        start_value = 70,
                        duration = 27.97,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        start_time = 22.03,
                        node_id = "enemy2/root",
                        start_value = 70,
                        duration = 27.97,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        start_time = 22.03,
                        node_id = "enemy3/root",
                        start_value = 70,
                        duration = 27.97,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        start_time = 22.03,
                        node_id = "enemy4/root",
                        start_value = 70,
                        duration = 27.97,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                    {
                        key_type = "tween",
                        start_time = 22.03,
                        node_id = "enemy5/root",
                        start_value = 70,
                        duration = 27.97,
                        property_id = "position_x",
                        easing = "outsine",
                    },
                },
            },
        },
        nodes = {
        },
        metadata = {
            fps = 60,
            layers = {
            },
            gui_path = "/game/collections/test.collection",
            settings = {
                font_size = 40,
            },
            gizmo_steps = {
            },
        },
    },
    type = "animation_editor",
    version = 1,
}