local evolved = require("evolved")
local fragments = require("fragments")

return evolved.builder()
	:name("damage_number")
	:prefab()
	:set(fragments.transform)
	:set(fragments.damage_number, 1)
	:set(fragments.lifetime, 1.3)
	:set(fragments.factory_url, "/entities#damage_number")
	:set(fragments.no_sync_game_object)
	:spawn()
