return {
    data = {
        nodes = {
        },
        animations = {
            {
                duration = 0.5,
                animation_id = "click",
                animation_keys = {
                    {
                        key_type = "tween",
                        start_value = 8,
                        end_value = -6,
                        property_id = "position_y",
                        duration = 0.14,
                        easing = "outsine",
                        node_id = "icon_arrow",
                    },
                    {
                        key_type = "tween",
                        end_value = -2,
                        property_id = "rotation_z",
                        duration = 0.15,
                        easing = "outsine",
                        node_id = "group_arrow",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1.1,
                        property_id = "scale_x",
                        duration = 0.15,
                        easing = "outsine",
                        node_id = "group_arrow",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1.1,
                        property_id = "scale_y",
                        duration = 0.15,
                        easing = "outsine",
                        node_id = "group_arrow",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1.7,
                        property_id = "color_a",
                        duration = 0.16,
                        easing = "outsine",
                        node_id = "root",
                    },
                    {
                        key_type = "tween",
                        start_value = 278,
                        end_value = 268,
                        property_id = "size_y",
                        duration = 0.16,
                        easing = "outquart",
                        node_id = "root",
                    },
                    {
                        key_type = "tween",
                        start_value = 278,
                        end_value = 298,
                        property_id = "size_x",
                        duration = 0.16,
                        easing = "outquart",
                        node_id = "root",
                    },
                    {
                        key_type = "tween",
                        start_value = -8,
                        end_value = -13,
                        property_id = "position_y",
                        duration = 0.18,
                        easing = "outsine",
                        node_id = "icon_arrow_shadow",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.15,
                        start_value = -2,
                        property_id = "rotation_z",
                        duration = 0.29,
                        easing = "outsine",
                        node_id = "group_arrow",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.15,
                        start_value = 1.1,
                        end_value = 1,
                        property_id = "scale_x",
                        duration = 0.29,
                        easing = "outsine",
                        node_id = "group_arrow",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.15,
                        start_value = 1.1,
                        end_value = 1,
                        property_id = "scale_y",
                        duration = 0.29,
                        easing = "outsine",
                        node_id = "group_arrow",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.16,
                        start_value = 1.7,
                        end_value = 1,
                        property_id = "color_a",
                        duration = 0.22,
                        easing = "outsine",
                        node_id = "root",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.16,
                        start_value = 298,
                        end_value = 278,
                        property_id = "size_x",
                        duration = 0.22,
                        easing = "insine",
                        node_id = "root",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.16,
                        start_value = 268,
                        end_value = 278,
                        property_id = "size_y",
                        duration = 0.22,
                        easing = "insine",
                        node_id = "root",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.18,
                        start_value = -13,
                        end_value = -8,
                        property_id = "position_y",
                        duration = 0.28,
                        easing = "outsine",
                        node_id = "icon_arrow_shadow",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.21,
                        start_value = -6,
                        end_value = 8,
                        property_id = "position_y",
                        duration = 0.29,
                        easing = "outback",
                        node_id = "icon_arrow",
                    },
                },
            },
        },
        metadata = {
            layers = {
                {
                    name = "game",
                    color = "73E84C",
                },
                {
                    name = "text",
                    color = "90D2F6",
                },
            },
            gui_path = "/gui/ui_button/ui_button.gui",
            is_frame_view = true,
            fps = 60,
            settings = {
                font_size = 40,
            },
            gizmo_steps = {
                time = 0.016667,
            },
        },
    },
    version = 1,
    format = "json",
    type = "animation_editor",
}