local evolved = require("evolved")
local fragments = require("fragments")

return evolved.builder()
	:prefab()
	:name("explosion")
	:set(fragments.transform)
	:set(fragments.collectionfactory_url, "/entities#explosion")
	:set(fragments.request_play_particlefx, "explosion")
	:set(fragments.lifetime, 0.4)
	:spawn()
