return {
    data = {
        animations = {
            {
                animation_id = "on_hover",
                animation_keys = {
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = -21.5,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "position_x",
                        start_value = -20,
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = -9,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = -1.5,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = 37,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "size_x",
                        start_value = 40,
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = 37,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "size_y",
                        start_value = 40,
                    },
                    {
                        duration = 0.19,
                        easing = "outback",
                        end_value = -20,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "position_x",
                        start_time = 0.27,
                        start_value = -21.5,
                    },
                    {
                        duration = 0.19,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "position_y",
                        start_time = 0.27,
                        start_value = -1.5,
                    },
                    {
                        duration = 0.19,
                        easing = "outback",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "size_x",
                        start_time = 0.27,
                        start_value = 37,
                    },
                    {
                        duration = 0.19,
                        easing = "outback",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "size_y",
                        start_time = 0.27,
                        start_value = 37,
                    },
                    {
                        duration = 0.27,
                        easing = "outquint",
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "position_y",
                        start_time = 0.27,
                        start_value = -10,
                    },
                    {
                        duration = 0.36,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "scale_y",
                        start_time = 0.27,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.48,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "scale_x",
                        start_time = 0.27,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.48,
                        easing = "outback",
                        end_value = 26,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "position_x",
                        start_time = 0.27,
                        start_value = -9,
                    },
                    {
                        duration = 0.27,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "position_x",
                        start_time = 0.79,
                        start_value = 26,
                    },
                },
                duration = 1.25,
            },
            {
                animation_id = "default",
                animation_keys = {
                },
                duration = 1,
            },
            {
                animation_id = "on_drag_start",
                animation_keys = {
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "on_drag_end",
                animation_keys = {
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "scale_x",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "drag",
                        property_id = "scale_y",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "drag_icon",
                        property_id = "color_a",
                    },
                },
                duration = 1,
                initial_state = "on_drag_start",
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "decore/properties_panel/property_entity_prefab.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}