local evolved = require("evolved")
local fragments = require("fragments")
local color = require("druid.color")

return evolved.builder()
	:prefab()
	:name("bullet")
	:set(fragments.transform)
	:set(fragments.collectionfactory_url, "/entities#bullet")
	:set(fragments.color, { ["/root#sprite"] = color.get_color("#EE6F6F") })
	:set(fragments.physics)
	:set(fragments.velocity)
	:set(fragments.spawn_on_destroy, require("entity.explosion.explosion"))
	:set(fragments.lifetime, 1)
	:set(fragments.collision)
	:set(fragments.on_collision_damage, 3)
	:set(fragments.on_collision_remove)
	:spawn()
