return {
    data = {
        nodes = {
        },
        animations = {
            {
                duration = 1,
                animation_id = "default",
                animation_keys = {
                },
            },
            {
                duration = 1,
                animation_id = "level_completed",
                animation_keys = {
                    {
                        key_type = "tween",
                        start_value = -960,
                        end_value = -1300,
                        property_id = "position_x",
                        duration = 0.42,
                        easing = "inback",
                        node_id = "W_Anchor",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1.3,
                        property_id = "scale_x",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "button_right/root",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1.3,
                        property_id = "scale_y",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "button_right/root",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.06,
                        start_value = 1,
                        property_id = "color_a",
                        duration = 0.37,
                        easing = "outsine",
                        node_id = "W_Anchor",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.12,
                        start_value = -100,
                        end_value = -305,
                        property_id = "position_y",
                        duration = 0.59,
                        easing = "outsine",
                        node_id = "group_time",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.24,
                        start_value = 1,
                        end_value = 1.3,
                        property_id = "scale_x",
                        duration = 0.52,
                        easing = "outsine",
                        node_id = "group_time",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.24,
                        start_value = 1,
                        end_value = 1.3,
                        property_id = "scale_y",
                        duration = 0.52,
                        easing = "insine",
                        node_id = "group_time",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.54,
                        start_value = -136,
                        end_value = -174.46,
                        property_id = "position_y",
                        duration = 0.34,
                        easing = "outsine",
                        node_id = "text_timer",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.57,
                        start_value = 2,
                        end_value = 2.5,
                        property_id = "scale_x",
                        duration = 0.29,
                        easing = "outback",
                        node_id = "text_timer",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.57,
                        start_value = 2,
                        end_value = 2.5,
                        property_id = "scale_y",
                        duration = 0.29,
                        easing = "outback",
                        node_id = "text_timer",
                    },
                },
            },
            {
                duration = 1,
                animation_id = "level_start",
                animation_keys = {
                    {
                        key_type = "tween",
                        start_value = -960,
                        end_value = -960,
                        property_id = "position_x",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "W_Anchor",
                    },
                    {
                        key_type = "tween",
                        start_value = -136,
                        end_value = -136,
                        property_id = "position_y",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "text_timer",
                    },
                    {
                        key_type = "tween",
                        start_value = -100,
                        end_value = -100,
                        property_id = "position_y",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "group_time",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1,
                        property_id = "color_a",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "W_Anchor",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1,
                        property_id = "scale_x",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "button_right/root",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1,
                        property_id = "scale_y",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "button_right/root",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1,
                        property_id = "scale_x",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "group_time",
                    },
                    {
                        key_type = "tween",
                        start_value = 1,
                        end_value = 1,
                        property_id = "scale_y",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "group_time",
                    },
                    {
                        key_type = "tween",
                        start_value = 2,
                        end_value = 2,
                        property_id = "scale_x",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "text_timer",
                    },
                    {
                        key_type = "tween",
                        start_value = 2,
                        end_value = 2,
                        property_id = "scale_y",
                        duration = 0.5,
                        easing = "outsine",
                        node_id = "text_timer",
                    },
                },
            },
        },
        metadata = {
            layers = {
                {
                    name = "game",
                    color = "73E84C",
                },
                {
                    name = "text",
                    color = "90D2F6",
                },
            },
            gui_path = "/entity/game_gui/game_gui.gui",
            is_frame_view = true,
            fps = 30,
            settings = {
                font_size = 30,
            },
            gizmo_steps = {
                time = 0.033333,
            },
        },
    },
    version = 1,
    format = "json",
    type = "animation_editor",
}
